version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /kube/worker-image
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: /terraform/examples/ec2-asg
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /terraform/examples/eks-new-cluster
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /terraform/examples/eks-existing-cluster
    schedule:
      interval: weekly
